name: gha-sumo-tb-android-concat-all-questions-answers
on:
  workflow_run:
    workflows: ["gha-sumo-tb-desktop-create-monthly-csv"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  concat:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout aaq repo
      uses: actions/checkout@v5
      with:
        repository: thunderbird/github-action-tbandroid-aaq
        path: aaq-data
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: '3.14' # Sets the version uv will use
        enable-cache: true      # Highly recommended for speed
    - name: Create virtual environment
      run: uv venv
    - name: Install dependencies
      run: uv pip install -r requirements.txt
    - name: Run concat script
      run: uv run ./sumo-tb-android-concat-all-questions-answers
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add CONCATENATED_FILES/
        git commit -m "Concatenate last 2 months of Android questions and answers" || echo "No changes to commit"
        git push
