name: gha-sumo-tb-desktop-concat-all-questions-answers

on:
  schedule:
    - cron: '0 3 * * *'   # 0300 UTC
    - cron: '0 9 * * *'   # 0900 UTC
    - cron: '0 15 * * *'  # 1500 UTC
    - cron: '0 22 * * *'  # 2200 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  concat:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout aaq repo
      uses: actions/checkout@v5
      with:
        repository: thunderbird/github-action-thunderbird-aaq
        path: aaq-data
    - name: Install uv
      run: pip install uv
    - name: Install dependencies
      run: uv pip install pandas
    - name: Run concat script
      run: uv run python3 sumo-tb-desktop-concat-all-questions-answers
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add CONCATENATED_FILES/
        git commit -m "Concatenate last 2 months questions and answers" || echo "No changes to commit"
        git push
